# Site settings
title: Dejan Angelov
author: Dejan Angelov
email: angelovdejan92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineer at GSIX. Student at Faculty of Computer Science and Engineering, Ss. Cyril
  and Methodius University in Skopje, Macedonia. Mainly working with PHP, but experimenting with many other technologies.
  Interested in software architecture, domain-driven design and electronics. People say i’m weird.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://angelovdejan.me" # the base hostname & protocol for your site
twitter_username: angelovdejan
github_username:  angelov

# Build settings
markdown: kramdown
